---
# General Vars
docker_daemon_options:
  storage-driver: "overlay2"
  data-root: "/opt/docker"

# Ubuntu Vars
ubuntu_docker_apt_release_channel: "stable"
ubuntu_docker_apt_repository: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

# RHEL Vars
