#### [DEBIAN] Check if reboot is needed ####
---
- name: "[DEBIAN] Check if reboot is needed"
  stat:
    path: /etc/fstab
  register: debianRebootRequired
  when: ansible_facts['os_family'] == "Debian"

#- name: "[DEBIAN] Reboot Required"
#  debug:
#    msg: "Reboot is Required on {{ ansible_hostname }}"
#  when: debianRebootRequired.stdout.find('No such file or directory') == -1

- name: "Output variable"
  ansible.builtin.debug:
    msg: "{{ debianRebootRequired.stat.exists }}"
  when: debianRebootRequired.stat.exists == true