---
- name: get target ready for ansible
  hosts: all
  remote_user: root
  vars_prompt:
    - name: user_name
      prompt: "Enter the user name:"
      private: no
    - name: user_password
      prompt: "Enter the user password:"
      private: yes

  tasks:
    - name: Create user
      ansible.builtin.user:
        name: "{{ user_name }}"
        state: present
        password: "{{ user_password | password_hash('sha512') }}"
        groups: wheel
        create_home: true

    - name: Create drop-in sudoers file
      file:
        path: /etc/sudoers.d/{{ user_name }}
        state: touch
        owner: root
        group: root
        mode: 0440

    - name: add line in sudoers file
      lineinfile:
        dest: /etc/sudoers.d/{{ user_name }}
        state: present
        line: 'ansibleuser ALL=(ALL) NOPASSWD:ALL'

    - name: create .ssh if it does not exist
      file:
        path: /home/{{ user_name }}/.ssh
        state: directory
        mode: '0700'
        owner: "{{ user_name }}"
        group: "{{ user_name }}"

    - name: copy authorized_keys file
      copy:
        src: authorized_keys
        dest: /home/{{ user_name }}/.ssh/authorized_keys
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: '0600'
        backup: yes

    - name: close down root ssh login
      ansible.builtin.lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "{{ item.regex }}"
        line: "{{ item.line }}"
      with_items:
        - regex: ^#PermitRootLogin
          line: PermitRootLogin no
        - regex: ^#PubkeyAuthentication yes
          line: PubkeyAuthentication yes
        - regex: ^#PasswordAuthentication yes
          line: PasswordAuthentication no
        - regex: ^#PermitEmptyPasswords no
          line: PermitEmptyPasswords no
      notify:
        - restart sshd after editing sshd_config

  handlers:
    - name: restart sshd after editing sshd_config
      ansible.builtin.systemd_service:
        name: sshd
        daemon_reload: true
        state: restarted