---

- name: Upgrade if RHEL Based
  include_tasks: rhelBased.yml
  when:
    - ansible_facts['os_family'] == "RedHat"

- name: Upgrade Debian Based
  include_tasks: debianBased.yml
  when:
    - ansible_facts['os_family'] == "Debian"