## Ansible file for upgrading all packages
# indentation: 2 spaces
---
- name: Playbook to update all packages on servers
  hosts: "{{ hostVar | default('all') }}"
  become: true
  roles:
    - role: updateOS
    - role: rebootCheck
